<a href="https://colab.research.google.com/github/chetan0220/ML-Sem6/blob/main/bengaluru_house_price.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [306]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [237]:
df = pd.read_csv('/content/drive/MyDrive/ML/ML Dataset/Bengaluru_House_Data.csv')
df.head()

area_type   availability                  location       size  \
0  Super built-up  Area         19-Dec  Electronic City Phase II      2 BHK   
1            Plot  Area  Ready To Move          Chikka Tirupathi  4 Bedroom   
2        Built-up  Area  Ready To Move               Uttarahalli      3 BHK   
3  Super built-up  Area  Ready To Move        Lingadheeranahalli      3 BHK   
4  Super built-up  Area  Ready To Move                  Kothanur      2 BHK   

   society total_sqft  bath  balcony   price  
0  Coomee        1056   2.0      1.0   39.07  
1  Theanmp       2600   5.0      3.0  120.00  
2      NaN       1440   2.0      3.0   62.00  
3  Soiewre       1521   3.0      1.0   95.00  
4      NaN       1200   2.0      1.0   51.00

In [238]:
df.shape

(13320, 9)

In [239]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   area_type     13320 non-null  object 
 1   availability  13320 non-null  object 
 2   location      13319 non-null  object 
 3   size          13304 non-null  object 
 4   society       7818 non-null   object 
 5   total_sqft    13320 non-null  object 
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB


In [240]:
df.describe()

bath       balcony         price
count  13247.000000  12711.000000  13320.000000
mean       2.692610      1.584376    112.565627
std        1.341458      0.817263    148.971674
min        1.000000      0.000000      8.000000
25%        2.000000      1.000000     50.000000
50%        2.000000      2.000000     72.000000
75%        3.000000      2.000000    120.000000
max       40.000000      3.000000   3600.000000

In [241]:
df.isna().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

## Handling Location

In [243]:
df['location'].unique()

array(['Electronic City Phase II', 'Chikka Tirupathi', 'Uttarahalli', ...,
       '12th cross srinivas nagar banshankari 3rd stage',
       'Havanur extension', 'Abshot Layout'], dtype=object)

In [244]:
df['location'].nunique()

1305

In [245]:
df['location'].mode()

0    Whitefield
Name: location, dtype: object

In [246]:
df['location'] = df['location'].fillna(df['location'].mode()[0])

In [247]:
df['location'].isna().sum()

0

In [248]:
df['location'].unique()

array(['Electronic City Phase II', 'Chikka Tirupathi', 'Uttarahalli', ...,
       '12th cross srinivas nagar banshankari 3rd stage',
       'Havanur extension', 'Abshot Layout'], dtype=object)

In [242]:
label_encoder = LabelEncoder()

In [249]:
df['location'] = label_encoder.fit_transform(df['location'])

In [250]:
df['location']

0         419
1         317
2        1179
3         757
4         716
         ... 
13315    1252
13316    1004
13317     972
13318     907
13319     396
Name: location, Length: 13320, dtype: int64

## Handling area_type

In [251]:
df['area_type'].nunique()

4

In [252]:
df['area_type'].unique()

array(['Super built-up  Area', 'Plot  Area', 'Built-up  Area',
       'Carpet  Area'], dtype=object)

In [253]:
df['area_type'] = label_encoder.fit_transform(df['area_type'])

In [254]:
df['area_type']

0        3
1        2
2        0
3        3
4        3
        ..
13315    0
13316    3
13317    0
13318    3
13319    3
Name: area_type, Length: 13320, dtype: int64

## Handling size

In [255]:
df['size'].nunique()

31

In [256]:
df['size'].unique()

array(['2 BHK', '4 Bedroom', '3 BHK', '4 BHK', '6 Bedroom', '3 Bedroom',
       '1 BHK', '1 RK', '1 Bedroom', '8 Bedroom', '2 Bedroom',
       '7 Bedroom', '5 BHK', '7 BHK', '6 BHK', '5 Bedroom', '11 BHK',
       '9 BHK', nan, '9 Bedroom', '27 BHK', '10 Bedroom', '11 Bedroom',
       '10 BHK', '19 BHK', '16 BHK', '43 Bedroom', '14 BHK', '8 BHK',
       '12 Bedroom', '13 BHK', '18 Bedroom'], dtype=object)

In [257]:
df['size'].isna().sum()

16

In [258]:
df['size'].value_counts()

size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
11 Bedroom       2
10 BHK           2
14 BHK           1
13 BHK           1
12 Bedroom       1
27 BHK           1
43 Bedroom       1
16 BHK           1
19 BHK           1
18 Bedroom       1
Name: count, dtype: int64

In [259]:
df['size'] = df['size'].fillna('2 BHK')

In [260]:
df['size'] = df['size'].str.split().str.get(0).astype(int)

In [261]:
df['size']

0        2
1        4
2        3
3        3
4        2
        ..
13315    5
13316    4
13317    2
13318    4
13319    1
Name: size, Length: 13320, dtype: int64

In [262]:
df['size'].isna().sum()

0

## Handling availability

In [263]:
df = df.drop('availability', axis = True)

## Handling society

In [264]:
df = df.drop('society', axis = True)

## Handling bath

In [265]:
df['bath'].value_counts()

bath
2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
13.0       3
11.0       3
16.0       2
27.0       1
40.0       1
15.0       1
14.0       1
18.0       1
Name: count, dtype: int64

In [266]:
df['bath'].isna().sum()

73

In [267]:
df['bath'] = df['bath'].fillna(df['bath'].mean().astype(int))

In [268]:
df['bath'].isna().sum()

0

## Handling balcony

In [269]:
df['balcony'].value_counts()

balcony
2.0    5113
1.0    4897
3.0    1672
0.0    1029
Name: count, dtype: int64

In [270]:
df['balcony'].nunique()

4

In [274]:
df['balcony'].unique()

array([ 1.,  3., nan,  2.,  0.])

In [272]:
df['balcony'].isna().sum()

609

In [275]:
df['balcony'] = df['balcony'].fillna(2)

In [276]:
df['balcony'].isna().sum()

0

## Handling total_sqft

In [279]:
df['total_sqft'].value_counts()

total_sqft
1200    843
1100    221
1500    205
2400    196
600     180
       ... 
3580      1
2461      1
1437      1
2155      1
4689      1
Name: count, Length: 2117, dtype: int64

In [280]:
df['total_sqft'].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      dtype=object)

In [281]:
def convert_range(x):
    temp = x.split('-')
    if len(temp) == 2:
        return (float(temp[0]) + float(temp[1])) / 2
    try:
        return float(x)
    except:
        return None

In [282]:
df['total_sqft'] = df['total_sqft'].apply(convert_range)

In [283]:
df['total_sqft'].unique()

array([1056. , 2600. , 1440. , ..., 1258.5,  774. , 4689. ])

In [284]:
df['total_sqft'].value_counts()

total_sqft
1200.0    843
1100.0    221
1500.0    206
2400.0    196
600.0     180
         ... 
3080.0      1
787.0       1
6613.0      1
502.0       1
4689.0      1
Name: count, Length: 1999, dtype: int64

In [285]:
df['total_sqft'].isna().sum()

46

In [286]:
df['total_sqft'] = df['total_sqft'].fillna(df['total_sqft'].mean())

In [287]:
df['total_sqft'].isna().sum()

0

In [288]:
df['total_sqft']

0        1056.0
1        2600.0
2        1440.0
3        1521.0
4        1200.0
          ...  
13315    3453.0
13316    3600.0
13317    1141.0
13318    4689.0
13319     550.0
Name: total_sqft, Length: 13320, dtype: float64

In [291]:
std_scaler = StandardScaler()

In [293]:
df['total_sqft'] = std_scaler.fit_transform(df['total_sqft'].values.reshape(-1, 1))

In [294]:
df.head()

area_type  location  size  total_sqft  bath  balcony   price
0          3       419     2   -0.407393   2.0      1.0   39.07
1          2       317     4    0.841577   5.0      3.0  120.00
2          0      1179     3   -0.096768   2.0      3.0   62.00
3          3       757     3   -0.031246   3.0      1.0   95.00
4          3       716     2   -0.290909   2.0      1.0   51.00

## Train Test Split

In [299]:
X = df.drop('price', axis = True)
y = df['price']

In [300]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

## Modelling

In [296]:
lr_model = LinearRegression()

In [301]:
lr_model.fit(X_train, y_train)

LinearRegression()

In [303]:
y_pred = lr_model.predict(X_test)
y_pred

array([ 66.11727418, 129.7508699 ,  68.42526402, ..., 207.95917868,
        72.65594799,  64.35157638])

In [307]:
r2_score(y_test, y_pred)

0.45677535772230526