In [69]:
import numpy as np
import pandas as pd
import seaborn as sns

In [67]:
np.__version__

'1.24.4'

In [68]:
pd.__version__

'2.0.3'

In [32]:
arr1 = np.array([1, 2, 3, 4], ndmin=2)
arr1

array([[1, 2, 3, 4]])

In [8]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr3 = np.array([[[1,2], [3, 4]]])
arr3

array([[[1, 2],
        [3, 4]]])

In [11]:
arr6 = np.array([1, 2, 3, 4, 5], ndmin=7)
arr6

array([[[[[[[1, 2, 3, 4, 5]]]]]]])

In [19]:
arr1[3]

4

In [22]:
arr1

array([1, 2, 3, 4])

In [27]:
print(arr1[1:4:2])

[2 4]


In [28]:
_ = arr2.copy()
_

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
concat_array = np.concatenate((array1, array2))
concat_array

array([1, 2, 3, 4, 5, 6])

In [49]:
arr7 = [1 ,2, 3, 4, 5, 6, 7, 8, 9]
np.reshape(arr7, (-1, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
array1 = np.array([[1, 2, 3]])
array2 = np.array([[4, 5, 6]])
hstacked_array = np.hstack((array1, array2))
hstacked_array

array([[1, 2, 3, 4, 5, 6]])

In [60]:
arr8 = [1 ,2, 3, 4, 5, 6, 7, 8, 9]
np.sort(arr8)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [62]:
arr = np.array([1, 2, 3, 4, 5])
arr_cp = arr.copy()
arr[0] = 24

print(arr)
print(arr_cp) 

[24  2  3  4  5]
[1 2 3 4 5]


In [63]:
arr = np.array([1, 2, 3, 4, 5])
arr_cp = arr.view()
arr[0] = 24

print(arr)
print(arr_cp) 

[24  2  3  4  5]
[24  2  3  4  5]


In [77]:
data = sns.load_dataset("titanic")
data

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]